apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-backend
spec:
  replicas: 2

  selector:
    matchLabels:
      app: vehicle-backend

  template:
    metadata:
      labels:
        app: vehicle-backend

    spec:
      containers:
      - name: backend

        image: suresh2003/vehicle-backend:${BUILD_NUMBER}

        ports:
        - containerPort: 8081

        env:
        - name: DB_HOST
          value: mysql

        - name: DB_USER
          value: root

        - name: DB_PASSWORD
          value: root

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
